# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CraigslistApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CraigslistApp

  target 'CraigslistAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CraigslistAppUITests' do
    # Pods for testing
  end
pod 'Alamofire', '~> 5.0.0-rc.2'
end
